# Сбор и обогащение датасета

In [38]:
import pandas as pd

## Сбор данных по заказам Olist (датасет Kaggle)

За основу мы взяли датасет с Kaggle: [Brazilian E-Commerce Public Dataset by Olist](https://www.kaggle.com/datasets/olistbr/brazilian-ecommerce)

In [39]:
orders = pd.read_csv(f'data/olist/olist_orders_dataset.csv')
orders

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00
...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28 00:00:00
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00

In [40]:
orders = orders[orders['order_status'] == 'delivered'].copy()
orders

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00
...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28 00:00:00
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00

In [41]:
date_cols = ['order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']

for col in date_cols:
    orders[col] = pd.to_datetime(orders[col])

In [42]:
order_items = pd.read_csv(f'data/olist/olist_order_items_dataset.csv')
order_items

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14
...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79

In [43]:
items_agg = order_items.groupby('order_id').agg(
    seller_id = ('seller_id', 'first'),
    product_id = ('product_id', 'first'),
    n_items = ('order_item_id', 'count'),
    total_price = ('price', 'sum'),
    total_freight = ('freight_value', 'sum'),
    avg_price = ('price', 'mean')
).reset_index()

items_agg

,order_id,seller_id,product_id,n_items,total_price,total_freight,avg_price
0,00010242fe8c5a6d1ba2dd792cb16214,48436dade18ac8b2bce089ec2a041202,4244733e06e7ecb4970a6e2683c13e61,1,58.90,13.29,58.90
1,00018f77f2f0320c557190d7a144bdd3,dd7ddc04e1b6c2c614352b383efe2d36,e5f2d52b802189ee658865ca93d83a8f,1,239.90,19.93,239.90
2,000229ec398224ef6ca0657da4fc703e,5b51032eddd242adc84c38acab88f23d,c777355d18b72b67abbeef9df44fd0fd,1,199.00,17.87,199.00
3,00024acbcdf0a6daa1e931b038114c75,9d7a1d34a5052409006425275ba1c2b4,7634da152a4610f1595efa32f14722fc,1,12.99,12.79,12.99
4,00042b26cf59d7ce69dfabb4e55b4fd9,df560393f3a51e74553ab94004ba5c87,ac6c3623068f30de03045865e4e10089,1,199.90,18.14,199.90
...,...,...,...,...,...,...,...
98661,fffc94f6ce00a00581880bf54a75a037,b8bc237ba3788b23da09c0f1f3a3288c,4aa6014eceb682077f9dc4bffebc05b0,1,299.99,43.41,299.99
98662,fffcd46ef2263f404302a634eb57f7eb,f3c38ab652836d21de61fb8314b69182,32e07fd915822b0765e448c4dd74c828,1,350.00,36.53,350.00
98663,fffce4705a9662cd70adb13d4a31832d,c3cfdc648177fdbbbb35635a37472c53,72a30483855e2eafc67aee5dc2560482,1,99.90,16.95,99.90
98664,fffe18544ffabc95dfada21779c9644f,2b3e4a2a3ea8e01938cabda2a3e5cc79,9c422a519119dcad7575db5af1ba540e,1,55.99,8.72,55.99
98665,fffe41c64501cc87c801fd61db3f6244,f7ccf836d21b2fb1de37564105216cc1,350688d9dc1e75ff97be326363655e01,1,43.00,12.79,43.00

In [44]:
payments = pd.read_csv(f'data/olist/olist_order_payments_dataset.csv')
payments

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45
...,...,...,...,...,...
103881,0406037ad97740d563a178ecc7a2075c,1,boleto,1,363.31
103882,7b905861d7c825891d6347454ea7863f,1,credit_card,2,96.80
103883,32609bbb3dd69b3c066a6860554a77bf,1,credit_card,1,47.77
103884,b8b61059626efa996a60be9bb9320e10,1,credit_card,5,369.54
103885,28bbae6599b09d39ca406b747b6632b1,1,boleto,1,191.58

In [45]:
pay_agg = payments.groupby('order_id').agg(
    payment_type = ('payment_type', 'first'),
    payment_installments = ('payment_installments', 'max'),
    payment_value = ('payment_value', 'sum')
).reset_index()
pay_agg

,order_id,payment_type,payment_installments,payment_value
0,00010242fe8c5a6d1ba2dd792cb16214,credit_card,2,72.19
1,00018f77f2f0320c557190d7a144bdd3,credit_card,3,259.83
2,000229ec398224ef6ca0657da4fc703e,credit_card,5,216.87
3,00024acbcdf0a6daa1e931b038114c75,credit_card,2,25.78
4,00042b26cf59d7ce69dfabb4e55b4fd9,credit_card,3,218.04
...,...,...,...,...
99435,fffc94f6ce00a00581880bf54a75a037,boleto,1,343.40
99436,fffcd46ef2263f404302a634eb57f7eb,boleto,1,386.53
99437,fffce4705a9662cd70adb13d4a31832d,credit_card,3,116.85
99438,fffe18544ffabc95dfada21779c9644f,credit_card,3,64.71
99439,fffe41c64501cc87c801fd61db3f6244,credit_card,1,55.79

In [46]:
reviews = pd.read_csv(f'data/olist/olist_order_reviews_dataset.csv')
reviews

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53
...,...,...,...,...,...,...,...
99219,574ed12dd733e5fa530cfd4bbf39d7c9,2a8c23fee101d4d5662fa670396eb8da,5,NaN,NaN,2018-07-07 00:00:00,2018-07-14 17:18:30
99220,f3897127253a9592a73be9bdfdf4ed7a,22ec9f0669f784db00fa86d035cf8602,5,NaN,NaN,2017-12-09 00:00:00,2017-12-11 20:06:42
99221,b3de70c89b1510c4cd3d0649fd302472,55d4004744368f5571d1f590031933e4,5,NaN,"Excelente mochila, entrega super rápida. Super...",2018-03-22 00:00:00,2018-03-23 09:10:43
99222,1adeb9d84d72fe4e337617733eb85149,7725825d039fc1f0ceb7635e3f7d9206,4,NaN,NaN,2018-07-01 00:00:00,2018-07-02 12:59:13
99223,efe49f1d6f951dd88b51e6ccd4cc548f,90531360ecb1eec2a1fbb265a0db0508,1,NaN,"meu produto chegou e ja tenho que devolver, po...",2017-07-03 00:00:00,2017-07-03 21:01:49

In [47]:
reviews_agg = reviews.groupby('order_id')['review_score'].mean().reset_index()
reviews_agg

                               order_id  review_score
0      00010242fe8c5a6d1ba2dd792cb16214           5.0
1      00018f77f2f0320c557190d7a144bdd3           4.0
2      000229ec398224ef6ca0657da4fc703e           5.0
3      00024acbcdf0a6daa1e931b038114c75           4.0
4      00042b26cf59d7ce69dfabb4e55b4fd9           5.0
...                                 ...           ...
98668  fffc94f6ce00a00581880bf54a75a037           5.0
98669  fffcd46ef2263f404302a634eb57f7eb           5.0
98670  fffce4705a9662cd70adb13d4a31832d           5.0
98671  fffe18544ffabc95dfada21779c9644f           5.0
98672  fffe41c64501cc87c801fd61db3f6244           5.0

[98673 rows x 2 columns]

In [48]:
customers = pd.read_csv(f'data/olist/olist_customers_dataset.csv')
customers

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP
...,...,...,...,...,...
99436,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,3937,sao paulo,SP
99437,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,6764,taboao da serra,SP
99438,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,60115,fortaleza,CE
99439,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,92120,canoas,RS
99440,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,6703,cotia,SP

In [49]:
sellers = pd.read_csv(f'data/olist/olist_sellers_dataset.csv')
sellers

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP
...,...,...,...,...
3090,98dddbc4601dd4443ca174359b237166,87111,sarandi,PR
3091,f8201cab383e484733266d1906e2fdfa,88137,palhoca,SC
3092,74871d19219c7d518d0090283e03c137,4650,sao paulo,SP
3093,e603cf3fec55f8697c9059638d6c8eb5,96080,pelotas,RS
3094,9e25199f6ef7e7c347120ff175652c3b,12051,taubate,SP

In [50]:
products = pd.read_csv(f'data/olist/olist_products_dataset.csv')
products

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0
...,...,...,...,...,...,...,...,...,...
32946,a0b7d5a992ccda646f2d34e418fff5a0,moveis_decoracao,45.0,67.0,2.0,12300.0,40.0,40.0,40.0
32947,bf4538d88321d0fd4412a93c974510e6,construcao_ferramentas_iluminacao,41.0,971.0,1.0,1700.0,16.0,19.0,16.0
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,cama_mesa_banho,50.0,799.0,1.0,1400.0,27.0,7.0,27.0
32949,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,60.0,156.0,2.0,700.0,31.0,13.0,20.0
32950,106392145fca363410d287a815be6de4,cama_mesa_banho,58.0,309.0,1.0,2083.0,12.0,2.0,7.0

In [51]:
geolocation = pd.read_csv(f'data/olist/olist_geolocation_dataset.csv')
geolocation

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP
...,...,...,...,...,...
1000158,99950,-28.068639,-52.010705,tapejara,RS
1000159,99900,-27.877125,-52.224882,getulio vargas,RS
1000160,99950,-28.071855,-52.014716,tapejara,RS
1000161,99980,-28.388932,-51.846871,david canabarro,RS
1000162,99950,-28.070104,-52.018658,tapejara,RS

In [52]:
geo_agg = geolocation.groupby('geolocation_zip_code_prefix').agg(
    lat = ('geolocation_lat', 'mean'),
    lng = ('geolocation_lng', 'mean')
).reset_index()

In [53]:
geo_agg_customers = geo_agg.rename(columns={'geolocation_zip_code_prefix': 'customer_zip_code_prefix', 'lat': 'customer_lat', 'lng': 'customer_lng'})
customers_geo = pd.merge(customers, geo_agg_customers, on='customer_zip_code_prefix', how='left')
customers_geo

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,customer_lat,customer_lng
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,-20.498489,-47.396929
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP,-23.727992,-46.542848
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP,-23.531642,-46.656289
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP,-23.499702,-46.185233
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP,-22.975100,-47.142925
...,...,...,...,...,...,...,...
99436,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,3937,sao paulo,SP,-23.586003,-46.499638
99437,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,6764,taboao da serra,SP,-23.615830,-46.768533
99438,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,60115,fortaleza,CE,-3.734569,-38.510534
99439,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,92120,canoas,RS,-29.949839,-51.168494
99440,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,6703,cotia,SP,-23.596732,-46.911994

In [54]:
geo_agg_sellers = geo_agg.rename(columns={'geolocation_zip_code_prefix': 'seller_zip_code_prefix', 'lat': 'seller_lat', 'lng': 'seller_lng'})
sellers_geo = pd.merge(sellers, geo_agg_sellers, on='seller_zip_code_prefix', how='left')
sellers_geo

,seller_id,seller_zip_code_prefix,seller_city,seller_state,seller_lat,seller_lng
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP,-22.893848,-47.061337
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP,-22.383437,-46.947927
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ,-22.909572,-43.177703
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP,-23.657242,-46.612831
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP,-22.964803,-46.534419
...,...,...,...,...,...,...
3090,98dddbc4601dd4443ca174359b237166,87111,sarandi,PR,-23.448041,-51.869960
3091,f8201cab383e484733266d1906e2fdfa,88137,palhoca,SC,-27.656421,-48.665840
3092,74871d19219c7d518d0090283e03c137,4650,sao paulo,SP,-23.657851,-46.676925
3093,e603cf3fec55f8697c9059638d6c8eb5,96080,pelotas,RS,-31.751072,-52.323202
3094,9e25199f6ef7e7c347120ff175652c3b,12051,taubate,SP,-23.012009,-45.585652

In [55]:
category_map = pd.read_csv(f'data/olist/product_category_name_translation.csv')
category_map

            product_category_name product_category_name_english
0                    beleza_saude                 health_beauty
1          informatica_acessorios         computers_accessories
2                      automotivo                          auto
3                 cama_mesa_banho                bed_bath_table
4                moveis_decoracao               furniture_decor
..                            ...                           ...
66                         flores                       flowers
67             artes_e_artesanato         arts_and_craftmanship
68                fraldas_higiene           diapers_and_hygiene
69  fashion_roupa_infanto_juvenil     fashion_childrens_clothes
70             seguros_e_servicos         security_and_services

[71 rows x 2 columns]

In [56]:
products = pd.merge(products, category_map, on='product_category_name', how='left')
products

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_name_english
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0,perfumery
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0,art
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0,sports_leisure
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0,baby
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0,housewares
...,...,...,...,...,...,...,...,...,...,...
32946,a0b7d5a992ccda646f2d34e418fff5a0,moveis_decoracao,45.0,67.0,2.0,12300.0,40.0,40.0,40.0,furniture_decor
32947,bf4538d88321d0fd4412a93c974510e6,construcao_ferramentas_iluminacao,41.0,971.0,1.0,1700.0,16.0,19.0,16.0,construction_tools_lights
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,cama_mesa_banho,50.0,799.0,1.0,1400.0,27.0,7.0,27.0,bed_bath_table
32949,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,60.0,156.0,2.0,700.0,31.0,13.0,20.0,computers_accessories
32950,106392145fca363410d287a815be6de4,cama_mesa_banho,58.0,309.0,1.0,2083.0,12.0,2.0,7.0,bed_bath_table

In [57]:
df = orders.copy()

df = pd.merge(df, items_agg, on='order_id', how='left')
df = pd.merge(df, pay_agg, on='order_id', how='left')
df = pd.merge(df, reviews_agg, on='order_id', how='left')
df = pd.merge(df, customers_geo[['customer_id', 'customer_unique_id', 'customer_state', 'customer_city', 'customer_lat', 'customer_lng']], on='customer_id', how='left')
df = pd.merge(df, sellers_geo[['seller_id', 'seller_state', 'seller_city', 'seller_lat', 'seller_lng']], on='seller_id', how='left')
df = pd.merge(df, products[['product_id', 'product_category_name_english', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm', 'product_photos_qty']], on='product_id', how='left')

df

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,seller_id,product_id,...,seller_state,seller_city,seller_lat,seller_lng,product_category_name_english,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_photos_qty
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,3504c0cb71d7fa48d967e0e4c94d59d9,87285b34884572647811a353c7ac498a,...,SP,maua,-23.680729,-46.444238,housewares,500.0,19.0,8.0,13.0,4.0
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,289cdb325fb7e7f891c38608bf9e0962,595fac2a385ac33a80bd5114aec74eb8,...,SP,belo horizonte,-19.807681,-43.980427,perfumery,400.0,19.0,13.0,19.0,1.0
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,4869f7a5dfa277a7dca6462dcf3b52b2,aa4383b373c6aca5d8797843e5594415,...,SP,guariba,-21.363502,-48.229601,auto,420.0,24.0,19.0,21.0,1.0
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,66922902710d126a0e7d26b0e3805106,d0b61bfb1de832b15ba9d266ca96e5b0,...,MG,belo horizonte,-19.837682,-43.924053,pet_shop,450.0,30.0,10.0,20.0,3.0
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,2c9e548be18521d1c43cde1c582c6de8,65266b2da20d04dbe00c5c2d3bb7859e,...,SP,mogi das cruzes,-23.543395,-46.262086,stationery,250.0,51.0,15.0,15.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96473,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28,e24fc9fcd865784fb25705606fe3dfe7,ac35486adb7b02598c182c2ff2e05254,...,SP,braganca paulista,-22.961694,-46.523854,health_beauty,1175.0,22.0,13.0,18.0,1.0
96474,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02,1f9ab4708f3056ede07124aad39a2554,f1d4ce8c6dd66c47bbaa8c6781c2a923,...,SP,tupa,-21.930548,-50.498348,baby,4950.0,40.0,10.0,40.0,4.0
96475,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27,d50d79cb34e38265a8649c383dcffd48,b80910977a37536adeddd63663f916ad,...,SP,sao paulo,-23.553642,-46.452661,home_appliances_2,13300.0,32.0,90.0,22.0,2.0
96476,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,a1043bafd471dff536d0c462352beb48,d1c427060a0f73f6b889a5c7c61f2ac4,...,MG,ilicinea,-20.940578,-45.827237,computers_accessories,6550.0,20.0,20.0,20.0,1.0
96477,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03,ececbfcff9804a2d6b40f589df8eef2b,006619bbed68b000c8ba3f8725d5409e,...,SP,franca,-20.496251,-47.418434,health_beauty,150.0,16.0,7.0,15.0,1.0

In [58]:
df['delay_days'] = (df['order_delivered_customer_date'] - df['order_estimated_delivery_date']).dt.total_seconds() / 86400
df['is_delayed'] = (df['delay_days'] > 0).astype(int)

df['seller_processing_days'] = (df['order_delivered_carrier_date'] - df['order_approved_at']).dt.total_seconds() / 86400
df['transit_days'] = (df['order_delivered_customer_date'] - df['order_delivered_carrier_date']).dt.total_seconds() / 86400

df['order_weekday'] = df['order_purchase_timestamp'].dt.dayofweek
df['order_month'] = df['order_purchase_timestamp'].dt.month
df['order_year'] = df['order_purchase_timestamp'].dt.year
df['order_hour'] = df['order_purchase_timestamp'].dt.hour

df['freight_ratio'] = df['total_freight'] / (df['total_price'] + 1e-9)

df['product_volume_cm3'] = (df['product_length_cm'] * df['product_height_cm'] * df['product_width_cm'])

df['low_review'] = (df['review_score'] <= 3).astype(int)

df

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,seller_id,product_id,...,is_delayed,seller_processing_days,transit_days,order_weekday,order_month,order_year,order_hour,freight_ratio,product_volume_cm3,low_review
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,3504c0cb71d7fa48d967e0e4c94d59d9,87285b34884572647811a353c7ac498a,...,0,2.366493,6.062650,0,10,2017,10,0.290764,1976.0,0
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,289cdb325fb7e7f891c38608bf9e0962,595fac2a385ac33a80bd5114aec74eb8,...,0,0.462882,12.039410,1,7,2018,20,0.191744,4693.0,0
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,4869f7a5dfa277a7dca6462dcf3b52b2,aa4383b373c6aca5d8797843e5594415,...,0,0.204595,9.178113,2,8,2018,8,0.120200,9576.0,0
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,66922902710d126a0e7d26b0e3805106,d0b61bfb1de832b15ba9d266ca96e5b0,...,0,3.745833,9.450498,5,11,2017,19,0.604444,6000.0,0
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,2c9e548be18521d1c43cde1c582c6de8,65266b2da20d04dbe00c5c2d3bb7859e,...,0,0.893113,1.937824,1,2,2018,21,0.438191,11475.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96473,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28,e24fc9fcd865784fb25705606fe3dfe7,ac35486adb7b02598c182c2ff2e05254,...,0,1.058310,7.159699,3,3,2017,9,0.181667,5148.0,0
96474,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02,1f9ab4708f3056ede07124aad39a2554,f1d4ce8c6dd66c47bbaa8c6781c2a923,...,0,1.425058,20.760579,1,2,2018,12,0.114923,16000.0,0
96475,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27,d50d79cb34e38265a8649c383dcffd48,b80910977a37536adeddd63663f916ad,...,0,1.241782,23.605451,6,8,2017,14,0.315646,63360.0,0
96476,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,a1043bafd471dff536d0c462352beb48,d1c427060a0f73f6b889a5c7c61f2ac4,...,0,3.749097,13.331840,0,1,2018,21,0.225513,8000.0,1
96477,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03,ececbfcff9804a2d6b40f589df8eef2b,006619bbed68b000c8ba3f8725d5409e,...,0,0.452442,6.622581,3,3,2018,20,0.268029,1680.0,0

In [59]:
import numpy as np

def get_distance(lat1, lon1, lat2, lon2):
    R = 6371
    lat1 = np.radians(lat1)
    lon1 = np.radians(lon1)
    lat2 = np.radians(lat2)
    lon2 = np.radians(lon2)

    a = np.sin((lat2 - lat1) / 2)**2 + np.cos(lat1) * np.cos(lat2) * np.sin((lon2 - lon1) / 2)**2
    return 2 * R * np.arctan2(np.sqrt(a), np.sqrt(1 - a))

df['distance_km'] = get_distance(df['seller_lat'].values, df['seller_lng'].values, df['customer_lat'].values, df['customer_lng'].values)
df

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,seller_id,product_id,...,seller_processing_days,transit_days,order_weekday,order_month,order_year,order_hour,freight_ratio,product_volume_cm3,low_review,distance_km
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,3504c0cb71d7fa48d967e0e4c94d59d9,87285b34884572647811a353c7ac498a,...,2.366493,6.062650,0,10,2017,10,0.290764,1976.0,0,18.576110
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,289cdb325fb7e7f891c38608bf9e0962,595fac2a385ac33a80bd5114aec74eb8,...,0.462882,12.039410,1,7,2018,20,0.191744,4693.0,0,851.495069
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,4869f7a5dfa277a7dca6462dcf3b52b2,aa4383b373c6aca5d8797843e5594415,...,0.204595,9.178113,2,8,2018,8,0.120200,9576.0,0,514.410666
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,66922902710d126a0e7d26b0e3805106,d0b61bfb1de832b15ba9d266ca96e5b0,...,3.745833,9.450498,5,11,2017,19,0.604444,6000.0,0,1822.226336
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,2c9e548be18521d1c43cde1c582c6de8,65266b2da20d04dbe00c5c2d3bb7859e,...,0.893113,1.937824,1,2,2018,21,0.438191,11475.0,0,29.676625
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96473,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28,e24fc9fcd865784fb25705606fe3dfe7,ac35486adb7b02598c182c2ff2e05254,...,1.058310,7.159699,3,3,2017,9,0.181667,5148.0,0,69.755064
96474,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02,1f9ab4708f3056ede07124aad39a2554,f1d4ce8c6dd66c47bbaa8c6781c2a923,...,1.425058,20.760579,1,2,2018,12,0.114923,16000.0,0,474.120037
96475,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27,d50d79cb34e38265a8649c383dcffd48,b80910977a37536adeddd63663f916ad,...,1.241782,23.605451,6,8,2017,14,0.315646,63360.0,0,967.847297
96476,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,a1043bafd471dff536d0c462352beb48,d1c427060a0f73f6b889a5c7c61f2ac4,...,3.749097,13.331840,0,1,2018,21,0.225513,8000.0,1,370.404482
96477,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03,ececbfcff9804a2d6b40f589df8eef2b,006619bbed68b000c8ba3f8725d5409e,...,0.452442,6.622581,3,3,2018,20,0.268029,1680.0,0,631.257275

## Обогащение данными по штатам Бразилии (IBGE)

In [60]:
import requests

r = requests.get('https://servicodados.ibge.gov.br/api/v1/localidades/estados', timeout=15)
raw = r.json()

states_df = pd.DataFrame([{'state_uf': s['sigla'], 'state_name': s['nome'], 'region': s['regiao']['nome'], 'region_sigla': s['regiao']['sigla'], 'ibge_id': str(s['id'])} for s in raw])

r = requests.get('https://servicodados.ibge.gov.br/api/v3/agregados/202/periodos/2010/variaveis/93?localidades=N3[all]', timeout=15)
pop_series = r.json()[0]['resultados'][0]['series']
pop_dict = {s['localidade']['id']: int(list(s['serie'].values())[0]) for s in pop_series}

states_df['population'] = states_df['ibge_id'].map(pop_dict)
states_df = states_df.drop(columns='ibge_id')
states_df

   state_uf           state_name        region region_sigla  population
0        RO             Rondônia         Norte            N     1562409
1        AC                 Acre         Norte            N      733559
2        AM             Amazonas         Norte            N     3483985
3        RR              Roraima         Norte            N      450479
4        PA                 Pará         Norte            N     7581051
5        AP                Amapá         Norte            N      669526
6        TO            Tocantins         Norte            N     1383445
7        MA             Maranhão      Nordeste           NE     6574789
8        PI                Piauí      Nordeste           NE     3118360
9        CE                Ceará      Nordeste           NE     8452381
10       RN  Rio Grande do Norte      Nordeste           NE     3168027
11       PB              Paraíba      Nordeste           NE     3766528
12       PE           Pernambuco      Nordeste           NE     8796448
13       AL              Alagoas      Nordeste           NE     3120494
14       SE              Sergipe      Nordeste           NE     2068017
15       BA                Bahia      Nordeste           NE    14016906
16       MG         Minas Gerais       Sudeste           SE    19597330
17       ES       Espírito Santo       Sudeste           SE     3514952
18       RJ       Rio de Janeiro       Sudeste           SE    15989929
19       SP            São Paulo       Sudeste           SE    41262199
20       PR               Paraná           Sul            S    10444526
21       SC       Santa Catarina           Sul            S     6248436
22       RS    Rio Grande do Sul           Sul            S    10693929
23       MS   Mato Grosso do Sul  Centro-Oeste           CO     2449024
24       MT          Mato Grosso  Centro-Oeste           CO     3035122
25       GO                Goiás  Centro-Oeste           CO     6003788
26       DF     Distrito Federal  Centro-Oeste           CO     2570160

In [61]:
state_extra = pd.read_csv('data/state_extra.csv')
state_extra

   state_uf  gdp_brl_billion  area_km2_thousands    hdi  urban_pct
0        SP             1990                 248  0.783       95.9
1        RJ              660                  44  0.761       96.7
2        MG              530                 587  0.731       86.8
3        RS              393                 282  0.746       87.0
4        PR              384                 199  0.749       87.6
5        BA              238                 565  0.660       75.3
6        SC              268                  96  0.774       89.0
7        GO              176                 340  0.735       91.7
8        PE              155                  98  0.673       81.9
9        CE              138                 149  0.682       79.7
10       AM              102                1571  0.674       82.3
11       PA               99                1248  0.646       76.0
12       MA               91                 332  0.639       69.8
13       ES              110                  46  0.740       92.3
14       MT              107                 903  0.725       86.5
15       MS               95                 358  0.729       87.9
16       PB               52                  57  0.658       77.3
17       RN               54                  53  0.684       82.0
18       AL               41                  28  0.631       76.8
19       PI               40                 252  0.646       73.8
20       DF              211                   6  0.824       96.5
21       SE               39                  22  0.665       84.3
22       RO               44                 238  0.690       82.2
23       TO               33                 278  0.699       79.0
24       AC               17                 165  0.663       77.6
25       AP               16                 143  0.708       85.1
26       RR               12                 225  0.707       77.1

In [62]:
states_full = pd.merge(states_df, state_extra, on='state_uf', how='left')
states_full['gdp_per_capita'] = (states_full['gdp_brl_billion'] * 1e9 / states_full['population']).round(0)
states_full['population_density'] = (states_full['population'] / (states_full['area_km2_thousands'] * 1000)).round(2)

states_full

,state_uf,state_name,region,region_sigla,population,gdp_brl_billion,area_km2_thousands,hdi,urban_pct,gdp_per_capita,population_density
0,RO,Rondônia,Norte,N,1562409,44,238,0.690,82.2,28162.0,6.56
1,AC,Acre,Norte,N,733559,17,165,0.663,77.6,23175.0,4.45
2,AM,Amazonas,Norte,N,3483985,102,1571,0.674,82.3,29277.0,2.22
3,RR,Roraima,Norte,N,450479,12,225,0.707,77.1,26638.0,2.00
4,PA,Pará,Norte,N,7581051,99,1248,0.646,76.0,13059.0,6.07
5,AP,Amapá,Norte,N,669526,16,143,0.708,85.1,23898.0,4.68
6,TO,Tocantins,Norte,N,1383445,33,278,0.699,79.0,23853.0,4.98
7,MA,Maranhão,Nordeste,NE,6574789,91,332,0.639,69.8,13841.0,19.80
8,PI,Piauí,Nordeste,NE,3118360,40,252,0.646,73.8,12827.0,12.37
9,CE,Ceará,Nordeste,NE,8452381,138,149,0.682,79.7,16327.0,56.73
10,RN,Rio Grande do Norte,Nordeste,NE,3168027,54,53,0.684,82.0,17045.0,59.77
11,PB,Paraíba,Nordeste,NE,3766528,52,57,0.658,77.3,13806.0,66.08
12,PE,Pernambuco,Nordeste,NE,8796448,155,98,0.673,81.9,17621.0,89.76
13,AL,Alagoas,Nordeste,NE,3120494,41,28,0.631,76.8,13139.0,111.45
14,SE,Sergipe,Nordeste,NE,2068017,39,22,0.665,84.3,18859.0,94.00
15,BA,Bahia,Nordeste,NE,14016906,238,565,0.660,75.3,16979.0,24.81
16,MG,Minas Gerais,Sudeste,SE,19597330,530,587,0.731,86.8,27045.0,33.39
17,ES,Espírito Santo,Sudeste,SE,3514952,110,46,0.740,92.3,31295.0,76.41
18,RJ,Rio de Janeiro,Sudeste,SE,15989929,660,44,0.761,96.7,41276.0,363.41
19,SP,São Paulo,Sudeste,SE,41262199,1990,248,0.783,95.9,48228.0,166.38
20,PR,Paraná,Sul,S,10444526,384,199,0.749,87.6,36766.0,52.49
21,SC,Santa Catarina,Sul,S,6248436,268,96,0.774,89.0,42891.0,65.09
22,RS,Rio Grande do Sul,Sul,S,10693929,393,282,0.746,87.0,36750.0,37.92
23,MS,Mato Grosso do Sul,Centro-Oeste,CO,2449024,95,358,0.729,87.9,38791.0,6.84
24,MT,Mato Grosso,Centro-Oeste,CO,3035122,107,903,0.725,86.5,35254.0,3.36
25,GO,Goiás,Centro-Oeste,CO,6003788,176,340,0.735,91.7,29315.0,17.66
26,DF,Distrito Federal,Centro-Oeste,CO,2570160,211,6,0.824,96.5,82096.0,428.36

In [63]:
states_customer = states_full[['state_uf', 'region', 'region_sigla', 'population', 'gdp_per_capita', 'hdi', 'urban_pct', 'population_density']].rename(columns=lambda c: f'customer_{c}' if c != 'state_uf' else 'customer_state')
states_seller = states_full[['state_uf', 'region', 'gdp_per_capita', 'hdi', 'urban_pct']].rename(columns=lambda c: f'seller_{c}' if c != 'state_uf' else 'seller_state')

df = pd.merge(df, states_customer, on='customer_state', how='left')
df = pd.merge(df, states_seller, on='seller_state', how='left')

df['hdi_diff'] = df['customer_hdi'] - df['seller_hdi']
df

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,seller_id,product_id,...,customer_population,customer_gdp_per_capita,customer_hdi,customer_urban_pct,customer_population_density,seller_region,seller_gdp_per_capita,seller_hdi,seller_urban_pct,hdi_diff
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,3504c0cb71d7fa48d967e0e4c94d59d9,87285b34884572647811a353c7ac498a,...,41262199,48228.0,0.783,95.9,166.38,Sudeste,48228.0,0.783,95.9,0.000
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,289cdb325fb7e7f891c38608bf9e0962,595fac2a385ac33a80bd5114aec74eb8,...,14016906,16979.0,0.660,75.3,24.81,Sudeste,48228.0,0.783,95.9,-0.123
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,4869f7a5dfa277a7dca6462dcf3b52b2,aa4383b373c6aca5d8797843e5594415,...,6003788,29315.0,0.735,91.7,17.66,Sudeste,48228.0,0.783,95.9,-0.048
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,66922902710d126a0e7d26b0e3805106,d0b61bfb1de832b15ba9d266ca96e5b0,...,3168027,17045.0,0.684,82.0,59.77,Sudeste,27045.0,0.731,86.8,-0.047
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,2c9e548be18521d1c43cde1c582c6de8,65266b2da20d04dbe00c5c2d3bb7859e,...,41262199,48228.0,0.783,95.9,166.38,Sudeste,48228.0,0.783,95.9,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96473,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28,e24fc9fcd865784fb25705606fe3dfe7,ac35486adb7b02598c182c2ff2e05254,...,41262199,48228.0,0.783,95.9,166.38,Sudeste,48228.0,0.783,95.9,0.000
96474,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02,1f9ab4708f3056ede07124aad39a2554,f1d4ce8c6dd66c47bbaa8c6781c2a923,...,41262199,48228.0,0.783,95.9,166.38,Sudeste,48228.0,0.783,95.9,0.000
96475,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27,d50d79cb34e38265a8649c383dcffd48,b80910977a37536adeddd63663f916ad,...,14016906,16979.0,0.660,75.3,24.81,Sudeste,48228.0,0.783,95.9,-0.123
96476,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,a1043bafd471dff536d0c462352beb48,d1c427060a0f73f6b889a5c7c61f2ac4,...,15989929,41276.0,0.761,96.7,363.41,Sudeste,27045.0,0.731,86.8,0.030
96477,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03,ececbfcff9804a2d6b40f589df8eef2b,006619bbed68b000c8ba3f8725d5409e,...,10444526,36766.0,0.749,87.6,52.49,Sudeste,48228.0,0.783,95.9,-0.034

## Обогащение данными погоды (Open-Meteo)

In [64]:
import openmeteo_requests
import requests_cache
from retry_requests import retry

cache_session = requests_cache.CachedSession('.openmeteo_cache', expire_after=-1)
openmeteo = openmeteo_requests.Client(session=retry(cache_session, retries=3, backoff_factor=0.5))

state_coords = pd.read_csv('data/state_coords.csv')
state_coords = dict(zip(state_coords['state_uf'], zip(state_coords['lat'], state_coords['lon'])))

In [65]:
weather_frames = []

for state_uf, (lat, lon) in state_coords.items():
    resp = openmeteo.weather_api('https://archive-api.open-meteo.com/v1/archive',
        params={'latitude': lat, 'longitude': lon, 'start_date': '2016-09-01', 'end_date': '2018-09-30', 'daily': ['precipitation_sum', 'temperature_2m_max', 'temperature_2m_min'], 'timezone': 'America/Sao_Paulo'})[0].Daily()

    dates = pd.date_range(start=pd.Timestamp(resp.Time(), unit='s', tz='America/Sao_Paulo').date(), periods=resp.Variables(0).ValuesAsNumpy().shape[0], freq='D').date

    wdf = pd.DataFrame({
        'date': dates,
        'precipitation_mm': resp.Variables(0).ValuesAsNumpy().round(2),
        'temp_avg_c': ((resp.Variables(1).ValuesAsNumpy() + resp.Variables(2).ValuesAsNumpy()) / 2).round(1),
        'heavy_rain': (resp.Variables(0).ValuesAsNumpy() > 20).astype(int),
    })

    wdf['state_uf'] = state_uf
    weather_frames.append(wdf)

weather_all = pd.concat(weather_frames, ignore_index=True)
weather_all

             date  precipitation_mm  temp_avg_c  heavy_rain state_uf
0      2016-09-01               0.0   17.500000           0       SP
1      2016-09-02               0.0   18.100000           0       SP
2      2016-09-03               1.0   20.299999           0       SP
3      2016-09-04               0.3   21.299999           0       SP
4      2016-09-05               0.4   19.100000           0       SP
...           ...               ...         ...         ...      ...
20515  2018-09-26               0.7   28.299999           0       RR
20516  2018-09-27              13.9   27.000000           0       RR
20517  2018-09-28               3.7   27.299999           0       RR
20518  2018-09-29               1.1   28.400000           0       RR
20519  2018-09-30               0.0   28.600000           0       RR

[20520 rows x 5 columns]

In [66]:
df['purchase_date'] = df['order_purchase_timestamp'].dt.date
df['delivery_date'] = df['order_delivered_customer_date'].dt.date

weather_purchase = weather_all.rename(columns={'state_uf': 'customer_state', 'date': 'purchase_date', 'precipitation_mm': 'purchase_precipitation_mm', 'temp_avg_c': 'purchase_temp_avg_c', 'heavy_rain': 'purchase_heavy_rain'})
df = pd.merge(df, weather_purchase, on=['customer_state', 'purchase_date'], how='left')

weather_delivery = weather_all.rename(columns={'state_uf': 'customer_state', 'date': 'delivery_date', 'precipitation_mm': 'delivery_precipitation_mm', 'temp_avg_c': 'delivery_temp_avg_c', 'heavy_rain': 'delivery_heavy_rain'})
df = pd.merge(df, weather_delivery, on=['customer_state', 'delivery_date'], how='left')

df

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,seller_id,product_id,...,seller_urban_pct,hdi_diff,purchase_date,delivery_date,purchase_precipitation_mm,purchase_temp_avg_c,purchase_heavy_rain,delivery_precipitation_mm,delivery_temp_avg_c,delivery_heavy_rain
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,3504c0cb71d7fa48d967e0e4c94d59d9,87285b34884572647811a353c7ac498a,...,95.9,0.000,2017-10-02,2017-10-10,5.000000,20.299999,0,2.4,25.299999,0.0
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,289cdb325fb7e7f891c38608bf9e0962,595fac2a385ac33a80bd5114aec74eb8,...,95.9,-0.123,2018-07-24,2018-08-07,2.500000,23.900000,0,1.2,24.799999,0.0
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,4869f7a5dfa277a7dca6462dcf3b52b2,aa4383b373c6aca5d8797843e5594415,...,95.9,-0.048,2018-08-08,2018-08-17,0.800000,25.200001,0,2.8,22.500000,0.0
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,66922902710d126a0e7d26b0e3805106,d0b61bfb1de832b15ba9d266ca96e5b0,...,86.8,-0.047,2017-11-18,2017-12-02,1.400000,26.400000,0,2.2,26.400000,0.0
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,2c9e548be18521d1c43cde1c582c6de8,65266b2da20d04dbe00c5c2d3bb7859e,...,95.9,0.000,2018-02-13,2018-02-16,3.200000,19.000000,0,0.9,20.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96473,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28,e24fc9fcd865784fb25705606fe3dfe7,ac35486adb7b02598c182c2ff2e05254,...,95.9,0.000,2017-03-09,2017-03-17,2.300000,23.600000,0,10.4,23.600000,0.0
96474,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02,1f9ab4708f3056ede07124aad39a2554,f1d4ce8c6dd66c47bbaa8c6781c2a923,...,95.9,0.000,2018-02-06,2018-02-28,2.300000,20.000000,0,0.1,23.000000,0.0
96475,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27,d50d79cb34e38265a8649c383dcffd48,b80910977a37536adeddd63663f916ad,...,95.9,-0.123,2017-08-27,2017-09-21,2.300000,23.100000,0,4.3,23.900000,0.0
96476,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,a1043bafd471dff536d0c462352beb48,d1c427060a0f73f6b889a5c7c61f2ac4,...,86.8,0.030,2018-01-08,2018-01-25,76.099998,24.100000,1,3.3,28.299999,0.0
96477,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03,ececbfcff9804a2d6b40f589df8eef2b,006619bbed68b000c8ba3f8725d5409e,...,95.9,-0.034,2018-03-08,2018-03-16,0.500000,19.100000,0,1.1,22.400000,0.0

## Обогащение праздниками Бразилии (python-holidays)

In [67]:
import holidays

br_holidays = {}
for year in [2016, 2017, 2018]:
    br_holidays.update(holidays.Brazil(years=year))

holiday_dates = set(br_holidays.keys())
holiday_dates

{datetime.date(2016, 1, 1),
 datetime.date(2016, 3, 25),
 datetime.date(2016, 4, 21),
 datetime.date(2016, 5, 1),
 datetime.date(2016, 9, 7),
 datetime.date(2016, 10, 12),
 datetime.date(2016, 11, 2),
 datetime.date(2016, 11, 15),
 datetime.date(2016, 12, 25),
 datetime.date(2017, 1, 1),
 datetime.date(2017, 4, 14),
 datetime.date(2017, 4, 21),
 datetime.date(2017, 5, 1),
 datetime.date(2017, 9, 7),
 datetime.date(2017, 10, 12),
 datetime.date(2017, 11, 2),
 datetime.date(2017, 11, 15),
 datetime.date(2017, 12, 25),
 datetime.date(2018, 1, 1),
 datetime.date(2018, 3, 30),
 datetime.date(2018, 4, 21),
 datetime.date(2018, 5, 1),
 datetime.date(2018, 9, 7),
 datetime.date(2018, 10, 12),
 datetime.date(2018, 11, 2),
 datetime.date(2018, 11, 15),
 datetime.date(2018, 12, 25)}

In [68]:
def days_to_next_holiday(date, holiday_dates):
    h = [h for h in holiday_dates if h > date]
    return (h[0] - date).days if h else None

purchase_dates = df['order_purchase_timestamp'].dt.date
delivery_dates = df['order_delivered_customer_date'].dt.date

df['purchase_is_holiday'] = purchase_dates.isin(holiday_dates).astype(int)
df['delivery_is_holiday'] = delivery_dates.isin(holiday_dates).astype(int)
df['days_to_next_holiday'] = purchase_dates.apply(lambda d: days_to_next_holiday(d, holiday_dates) if pd.notna(d) else None)

df

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,seller_id,product_id,...,delivery_date,purchase_precipitation_mm,purchase_temp_avg_c,purchase_heavy_rain,delivery_precipitation_mm,delivery_temp_avg_c,delivery_heavy_rain,purchase_is_holiday,delivery_is_holiday,days_to_next_holiday
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,3504c0cb71d7fa48d967e0e4c94d59d9,87285b34884572647811a353c7ac498a,...,2017-10-10,5.000000,20.299999,0,2.4,25.299999,0.0,0,0,396
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,289cdb325fb7e7f891c38608bf9e0962,595fac2a385ac33a80bd5114aec74eb8,...,2018-08-07,2.500000,23.900000,0,1.2,24.799999,0.0,0,0,101
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,4869f7a5dfa277a7dca6462dcf3b52b2,aa4383b373c6aca5d8797843e5594415,...,2018-08-17,0.800000,25.200001,0,2.8,22.500000,0.0,0,0,86
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,66922902710d126a0e7d26b0e3805106,d0b61bfb1de832b15ba9d266ca96e5b0,...,2017-12-02,1.400000,26.400000,0,2.2,26.400000,0.0,0,0,349
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,2c9e548be18521d1c43cde1c582c6de8,65266b2da20d04dbe00c5c2d3bb7859e,...,2018-02-16,3.200000,19.000000,0,0.9,20.000000,0.0,0,0,262
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96473,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28,e24fc9fcd865784fb25705606fe3dfe7,ac35486adb7b02598c182c2ff2e05254,...,2017-03-17,2.300000,23.600000,0,10.4,23.600000,0.0,0,0,603
96474,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02,1f9ab4708f3056ede07124aad39a2554,f1d4ce8c6dd66c47bbaa8c6781c2a923,...,2018-02-28,2.300000,20.000000,0,0.1,23.000000,0.0,0,0,269
96475,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27,d50d79cb34e38265a8649c383dcffd48,b80910977a37536adeddd63663f916ad,...,2017-09-21,2.300000,23.100000,0,4.3,23.900000,0.0,0,0,432
96476,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,a1043bafd471dff536d0c462352beb48,d1c427060a0f73f6b889a5c7c61f2ac4,...,2018-01-25,76.099998,24.100000,1,3.3,28.299999,0.0,0,0,298
96477,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03,ececbfcff9804a2d6b40f589df8eef2b,006619bbed68b000c8ba3f8725d5409e,...,2018-03-16,0.500000,19.100000,0,1.1,22.400000,0.0,0,0,239

In [69]:
df.to_csv('data/olist_enriched.csv', index=False)